
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-wordle
spec: 
  selector:
    matchLabels:
      app: wordle
  replicas: 1
  template:
    metadata:
      labels:
        app: wordle
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: wordle
          image: docker.io/jdbennet2001/node-wordle
          env:
            - name: "SAMPLE"
              value: "50000"
          volumeMounts:
            - name: task-pv-storage
              mountPath: /data

--- 

apiVersion: v1
kind: Service
metadata:
  name: wordle-service
spec:
  type: NodePort
  selector:
    app: wordle
  ports:
  - protocol: TCP
    port: 3080 # CLUSTERIP PORT
    targetPort: 3000 # POD PORT WHICH APPLICATION IS RUNNING ON 
    nodePort: 32222 # PUBLIC PORT, SINGLE NODE ONLY!

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Mi
