apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-wordle
spec:
  selector:
    matchLabels:
      app: wordle
  replicas: 1
  template:
    metadata:
      labels:
        app: wordle
    spec:
      containers:
      - name: wordle
        image: ghcr.io/jdbennet2001/node-wordle:latest
        env:
        - name: "SAMPLE"
          value: "50000"
      imagePullSecrets:
      - name: ghcr-secret

--- 

apiVersion: v1
kind: Service
metadata:
  name: wordle-service
spec:
  type: NodePort
  selector:
    app: wordle
  ports:
  - protocol: TCP
    port: 3080 # CLUSTERIP PORT
    targetPort: 3000 # POD PORT WHICH APPLICATION IS RUNNING ON 
    nodePort: 32222 # PUBLIC PORT, SINGLE NODE ONLY!