replicaCount: 1

image:
  repository: ghcr.io/jdbennet2001/node-wordle:latest
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: ghcr-secret

service:
  type: ClusterIP

# Additional parameters if needed
