apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordle
  labels:
    app: wordle
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wordle
  template:
    metadata:
      labels:
        app: wordle
    spec:
      containers:
      - name: wordle
        image: ghcr.io/jdbennet2001/node-wordle:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
