name: Component Pipeline

on:
  workflow_dispatch:
    inputs:
      componentYAML:
        description: 'Path to the component YAML file'
        required: false
        default: 'pipeline.yaml'
      systemTest:
        description: 'Run system tests'
        required: false
        default: true
        type: boolean
  workflow_call:
    inputs:
      componentYAML:
        description: 'Path to the component YAML file'
        required: false
        default: 'pipeline.yaml'
        type: string
      systemTest:
        description: 'Run system tests'
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display inputs
        run: |
          echo "Component YAML Name: ${{ github.event.inputs.componentYAMLName }}"
          echo "System Test: ${{ github.event.inputs.systemTest }}"


      - name: Run Component Pipeline
        run: |
          echo "Using component YAML: ${{ inputs.componentYAML }}"
          if [ "${{ inputs.systemTest }}" = true ]; then
            echo "Running system tests"
            # Add system test commands here
          else
            echo "Skipping system tests"
          fi
        env:
          COMPONENT_YAML: ${{ inputs.componentYAML }}
          SYSTEM_TEST: ${{ inputs.systemTest }}
