name: Build, Test, and Deploy Docker Image

# Allows manual triggering of the workflow
on:
  workflow_dispatch:

jobs:
  build-test-deploy:
    name: Build, Test, and Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN_USER }}
          password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}

      - name: Build Docker image
        run: docker build -t jdbennet2001/node-wordle .

      - name: Run Docker container locally
        run: docker run -d -p 3000:3000 --name wordle jdbennet2001/node-wordle:latest

      - name: Wait for the service to be up
        run: sleep 30 # Adjust the time as necessary for your service to be up and running

      - name: Display Docker information
        run: docker ps


      - name: Test the web interface
        run: |
          RESPONSE=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:3000)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Health check failed with status code $RESPONSE"
            exit 1
          else
            echo "Health check passed with status code $RESPONSE"
          fi


      - name: Get build number
        id: build-number
        run: |
          if [ -f .build-number ]; then
            echo "Build number file exists."
            BUILD_NUMBER=$(cat .build-number)
          else
            echo "Build number file does not exist. Starting at 0."
            BUILD_NUMBER=0
          fi
          BUILD_NUMBER=$((BUILD_NUMBER + 1))
          echo $BUILD_NUMBER > .build-number
          echo "::set-output name=BUILD_NUMBER::$BUILD_NUMBER"

      - name: Commit build number
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .build-number
          git commit -m "Increment build number to ${{ steps.build-number.outputs.BUILD_NUMBER }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop and remove Docker container
        run: docker rm -f wordle

      - name: Extract Git Commit SHA
        id: vars
        run: echo "GIT_COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Tag Docker image with SHA
        run: docker tag jdbennet2001/node-wordle:latest jdbennet2001/node-wordle:${{ env.GIT_COMMIT_SHA }}

      - name: Push Docker image to DockerHub
        run: docker push jdbennet2001/node-wordle:latest