name: Build, Test, and Deploy Docker Image

# Allows manual triggering of the workflow
on:
  workflow_dispatch:

jobs:
  build-test-deploy:
    name: Build, Test, and Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN_USER }}
          password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}

      - name: Build Docker image
        run: docker build -t jdbennet2001/node-wordle .