name: Build, Test, and Deploy Docker Image

# Allows manual triggering of the workflow
on:
  workflow_dispatch:

jobs:
  build-test-deploy:
    name: Build, Test, and Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN_USER }}
          password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}

      - name: Build Docker image
        run: docker build -t jdbennet2001/node-wordle .

      - name: Run Docker container locally
        run: docker run -d -p 8080:80 --name wordle jdbennet2001/node-wordle:latest

      - name: Wait for the service to be up
        run: sleep 30 # Adjust the time as necessary for your service to be up and running

      - name: Display Docker information
        run: docker ps

      - name: Display curl information
        run: curl http://localhost:3000

      - name: Test the web interface
        run: |
          RESPONSE=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:3000)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Health check failed with status code $RESPONSE"
            exit 1
          else
            echo "Health check passed with status code $RESPONSE"
          fi

      - name: Stop and remove Docker container
        run: docker rm -f wordle