name: Trigger Component Test

on:
  workflow_dispatch:
    inputs:
      componentYAMLName:
        description: 'Name of the component YAML'
        required: true
        default: 'component-trigger.yaml'
      systemTest:
        description: 'Run system test'
        required: true
        default: false
        type: boolean

jobs:

  initialTests:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Display inputs
          run: |
            echo "Component YAML Name: ${{ github.event.inputs.componentYAMLName }}"
            echo "System Test: ${{ github.event.inputs.systemTest }}"

  call-workflow-passing-data:
    uses: jdbennet2001/wordle/.github/workflows/componentPipeline.yaml@main
    with:
      componentYAML: ${{ github.event.inputs.componentYAMLName }}
      systemTest: ${{ github.event.inputs.systemTest }}
